### ISSUE TITLE
Receive pushes when app is closed

### ISSUE THREAD

**Issue by lawjeremy** [morinel/gcmpush#1]
Is it possible with this library to receive pushes when the app is closed and out of memory?

**Comment by morinel** [comment]
Sure, use gcm.getLastData() when the app starts or resumes to retrieve the data from the last push notification and act accordingly in your app. See the example for how this could work.

**Comment by lawjeremy** [comment]
What I'd like to do is pop up a notification while the app is still closed, prompting them to open it. Is this possible?

**Comment by morinel** [comment]
Well, the notification will be shown in the normal way (either at the top, or as a alertbox you have to click to open the app / dismiss it) If you click it, the app will open / resume and then you should use gcm.getLastData() to do anything specific to process the data in the notification itself.

**Comment by lawjeremy** [comment]
The problem I'm having is that I don't get anything on my device (in the tray or an alert)  from the push until I open the app.

**Comment by morinel** [comment]
Check Settings > Notifications > Your App whether notifications are allowed and how they are displayed.

Did you allow the app to show notifications when first installed on your device?

**Comment by morinel** [comment]
Duh, I'm on iPhone now

**Comment by morinel** [comment]
Do you see the notification being received by the app in logcat?

**Comment by lawjeremy** [comment]
My app is allowed to show notifications. I don't see anything in logcat that looks like a notification, what should I be looking for?

**Comment by morinel** [comment]
Search for "Push notification received" for log category GCMIntentService.

**Comment by lawjeremy** [comment]
Digging through logcat helped me find the problem

    [ 07-02 20:52:56.441 25483:25502 D/GCMIntentService ]
    (IntentService[GCMIntentService--1]) [5,647] Message received but no message so will make this silent

I had my message key in the payload capitalized

    "Message": "Hello World"

There's half a day I'll never get back. Thanks for all your help!
