### ISSUE TITLE
LED light setting not available

### ISSUE THREAD

**Issue by RavindraChherke** [morinel/gcmpush#18]
Hi, 

Could you please add LED light setting for the notifications.

**Comment by morinel** [comment]
What kind of settings would you like to see?

See [javadoc](http://developer.android.com/reference/android/app/Notification.html#FLAG_SHOW_LIGHTS).

**Comment by RavindraChherke** [comment]
FLAG_SHOW_LIGHTS
To flash the LED, pass the number of milliseconds that it should be on and off to ledOnMS and ledOffMS.
Thanks.

**Comment by morinel** [comment]
Please let me know whether release 1.4 works for you

**Comment by RavindraChherke** [comment]
Hi,

I used the same values given in example for LED timing but always getting.
Invalid setting ledOn, should be Integer
Invalid setting ledOff, should be Integer

**Comment by morinel** [comment]
Please show me the code you're using
