### ISSUE TITLE
Release 1.4 is not detected

### ISSUE THREAD

**Issue by macasfaj** [morinel/gcmpush#22]
Hi, I've installed into my project the 1.4 release and AppC Studio doesn't detect it.

With 1.3 works 100%

Thx.

**Comment by morinel** [comment]
What does your tiapp.xml say?

**Comment by macasfaj** [comment]
This release is not available. Only 1.3. AppC ignores 1.4.

**Comment by morinel** [comment]
Works for me
```
$ gittio update
[INFO]  nl.vanvianen.android.gcm searching...
[ERROR] nl.vanvianen.android.gcm:commonjs no distributable available
[INFO]  nl.vanvianen.android.gcm@1.4:android downloading...
[INFO]  nl.vanvianen.android.gcm@1.4:android installing...
[INFO]  nl.vanvianen.android.gcm@1.4:android updating in tiapp.xml
[INFO]  nl.vanvianen.android.gcm@1.4:android installed
```

**Comment by lawjeremy** [comment]
It works for me as well, when installed using Appcelerator Studio. I have had this problem before when I tried to manually extract a module into the modules directory.

**Comment by macasfaj** [comment]
Does your tiapp.xml show 1.4 version? I only see 1.3, but 1.4 is installed.

**Comment by a-imai** [comment]
Try this.

at manifest
`apiversion: 3`
Change as follows,
`apiversion: 2`

Then build again, and install into your project.

**Comment by mvrilo** [comment]
This worked for me @a-imai :+1:

**Comment by soramister** [comment]
With @a-imai solution, I can add the module. Thanks!

**Comment by kerbooo** [comment]
Thank you  @a-imai your trick worked for me too.
