### ISSUE TITLE
Module not supported

### ISSUE THREAD

**Issue by yankovalera** [morinel/gcmpush#28]
Hello, after I installed this module from gittio I'm getting some error - it seems to be unsupported by Ti SDK 5.2.0.GA. See attachment
![screen shot 2016-03-09 at 14 55 01](https://cloud.githubusercontent.com/assets/5551939/13637571/55461dee-e608-11e5-8f74-09e2063532e4.png)
.

**Comment by kerbooo** [comment]
Yes this is same for me too.

**Comment by morinel** [comment]
Try using the command-line interface, it will work there

**Comment by kerbooo** [comment]
So How can I use command-line interface? Thank you in advance.

**Comment by morinel** [comment]
See http://docs.appcelerator.com/platform/latest/#!/guide/Titanium_Command-Line_Interface_Reference
