### ISSUE TITLE
Grouping issue

### ISSUE THREAD

**Issue by kerbooo** [morinel/gcmpush#30]
My settings as below and working like a charm. But when I send more than one notification my remote server, Android 5.1 (this version is my phone version) shows only last notification. Where is my fault?

```
senderId : 'xxxxxx', //> It's the same as your project id
notificationSettings : {
     sound : 'custom.mp3', 
     smallIcon : 'notification.png', 
     largeIcon : 'appicon.png', 
     vibrate : true, 
     nsistent : false, 
     group : 'JLB', 
     localOnly : false,
     priority : +2,
     bigText : true,
     ledOn : 200,
     ledOff : 300
}
```

And how can I clear my last notification data?

**Comment by morinel** [comment]
Remove the ```group``` setting if you don't want to group consecutive messages into one.

Use ```gcm.clearLastData()``` to clear the last notification data.

**Comment by kerbooo** [comment]
I removed group line but nothing change. Still last notification shows
only. Please help me?
17 Mar 2016 16:12 tarihinde "Jeroen van Vianen" <notifications@github.com>
yazdı:

**Comment by morinel** [comment]
Check with ```adb logcat``` and your device connected via USB whether the different notification messages are actually received and processed as expected.

**Comment by kerbooo** [comment]
Yes I see 2 different recevied notification on console log.

Also I show first notification on android notification area then last one
is showing inside of first. They are not showing seperaretly.
17 Mar 2016 17:50 tarihinde "Jeroen van Vianen" <notifications@github.com>
yazdı:

**Comment by kerbooo** [comment]
Yes this approach for develepor's build. I modified source codes to my
needs. If you want I can send my own builds to you.
17 Mar 2016 18:22 tarihinde "Kerberos Spam" <kerberospam@gmail.com> yazdı:
