### ISSUE TITLE
Last notification replace the previous

### ISSUE THREAD

**Issue by mcvendrell** [morinel/gcmpush#38]
Hi guy.

Thanks for this module, it is really great. I noticed that, when you send more than one notification, only the last is shown on the device (the old is replaced). This seems to be happening because you hardcoded this:

`((NotificationManager)` getSystemService(Context.NOTIFICATION_SERVICE)).notify(1, notification);`

And I see later that @kerbooo made a pull request but it is waiting for approval.

I leave this message here for future references (the kerbooo "issue" is not well "titled" for searching

**Comment by morinel** [comment]
I just released version 1.5 which hopefully fixes the issue for you.

**Comment by mcvendrell** [comment]
Thanks, yesterday I get the fixes from @kerbooo working and really fixed the issue. I will download your version to test it again.
