### ISSUE TITLE
Notifications when app is closed

### ISSUE THREAD

**Issue by giorgiopagnoni** [morinel/gcmpush#4]
Can we receive and handle notifications when the app is closed?

**Comment by morinel** [comment]
Yes, the notification will be shown and you can process any data stored with the following code. This code fragment should be called when starting / resuming the app. You can then act on this data appropriately.
```js
var lastData = gcm.getLastData();
if (lastData) {
	Ti.API.info("Last notification received " + JSON.stringify(lastData));
	gcm.clearLastData();
}
```
See the example.

**Comment by giorgiopagnoni** [comment]
Thank you. I was used to the gcm module from iamyellow where I could personalize my notification in the gcm.js file. 
Can I do that here? Like set the notification flags, priority, title, etc?

**Comment by morinel** [comment]
This is the stuff that you can currently configure: smallIcon, largeIcon, sound, vibrate, or set from push itself: title, message, ticker.

If there's anything else you'd like to specify, let me know.

**Comment by giorgiopagnoni** [comment]
I'm rather new to these kind of things, so sorry if I'm being dense.

If possible, I'd like to set flags like FLAG_SHOW_LIGHTS and FLAG_INSISTENT. Are they *conditionally* settable right now? I send all my notifications from a PHP server (code snippet below).

For example, some of my notifications need to have the FLAG_INSISTENT set, so I used to add a boolean to the message which I could then check in my Titanium code (in gcm.js) when receiving the notification (even when the app was closed).

As far as I understand this isn't possible with your code?

```php
define( 'API_ACCESS_KEY', '***************' );
$registrationIds = array("'***************'");

$msg = array
(
    'message'       => 'message',
    'title'         => 'title title',
    'subtitle'      => 'This is a subtitle. subtitle',
    'tickerText'    => 'Ticker text here...Ticker text here...Ticker text here',
    'insistent' => 1
);

$fields = array
(
    'registration_ids'  => $registrationIds,
    'data'              => $msg
);

$headers = array
(
    'Authorization: key=' . API_ACCESS_KEY,
    'Content-Type: application/json'
);

$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch );
curl_close( $ch );

echo $result;
```

**Comment by morinel** [comment]
Lights are only the default:

```java
notification.defaults |= Notification.DEFAULT_LIGHTS;
```
So they cannot be configured currently.

Give me some time to set the insistent flag on the notification.

**Comment by giorgiopagnoni** [comment]
Thank you. If you can make it conditional, please go ahead when and if you have some free time, but if you can't make it conditional it won't suit my purpose so don't bother. I don't need that flag on all my notifications.

**Comment by morinel** [comment]
Please check out new version 1.1, the setting insistent should probably be specified as a boolean, not as an int

**Comment by giorgiopagnoni** [comment]
Thank you!
