### ISSUE TITLE
Can't install the module

### ISSUE THREAD

**Issue by arildojr** [morinel/gcmpush#43]
Hi,

I tried to install the module through "Help" -> "Install Mobile Module" and it gets succesfully installed but it doesn't list in tiapp.xml. I tried with versions 1.6, 1.5 and 1.3. Thus, I can't compile the module.
Can someone help me? Provide me a link with a valid dist zip?

Platform: Android
Titanium SDK: 5.3.0.GA
Appcelerator Studio: 4.6.0.201605201934
Mac OS X El Capitan

Thank's

**Comment by antonioduran** [comment]
Hello. Good evening. I have the same situation as @arildojr.

**Comment by m1ga** [comment]
You can either use gittio to install it:
`gittio install nl.vanvianen.android.gcm`
have a look here on how to install gittio: http://gitt.io/cli (it's worth it :) )

or download to compiled version from here:
https://github.com/morinel/gcmpush/releases
and place it in the root application folder. Next time you compile the app it will unzip it. Then you just add
`<module platform="android">nl.vanvianen.android.gcm</module>`
to your <modules> section in the tiapp.xml

or follow this guide: http://docs.appcelerator.com/platform/latest/#!/guide/Using_a_Module

Hope that helps!
