### ISSUE TITLE
Error: Alloy is not defined

### ISSUE THREAD

**Issue by jonasfunk** [morinel/gcmpush#48]
I am facing the same issue [as described here on JIRA](https://jira.appcelerator.org/browse/ALOY-1504): 
1. App is closed manually in background 
2. There is a notification in notification bar for the app
3. App is opened by tapping on the notification.
4. An error with "Alloy is not defined" is displayed. 

Has anyone experienced the same issue, but somehow managed to find a solution?

**Comment by morinel** [comment]
I don't think this is specific to this module.
