### ISSUE TITLE
Module not compatible with SDK 5.4.0 ??

### ISSUE THREAD

**Issue by fahad86** [morinel/gcmpush#49]
[https://s3-ap-southeast-1.amazonaws.com/uploads-ap.hipchat.com/56929/750866/xIoboi34Wmlvz8v/Screen%20Shot%202016-08-24%20at%2011.09.22%20AM.png](https://s3-ap-southeast-1.amazonaws.com/uploads-ap.hipchat.com/56929/750866/xIoboi34Wmlvz8v/Screen%20Shot%202016-08-24%20at%2011.09.22%20AM.png)

Tried compiling the module with 5.4.0, with minsdk set to 5.4.0 but still having the same issue.

**Comment by krem06** [comment]
Downloaded the last zip released (1.7) but no luck either... Following my log:

[WARN] :   Could not find a valid Titanium module id=nl.vanvianen.android.gcm version=1.7 platform=android deploy-type=development
[ERROR] :  Could not find all required Titanium Modules:
[ERROR] :     id: nl.vanvianen.android.gcm	 version: 1.7	 platform: android	 deploy-type: development

I installed the module like always, with Titanium Studio built-in module uploader.

**Comment by fahad86** [comment]
@krem06 any more luck?

**Comment by krem06** [comment]
1.3 appears in my list of modules with Titanium SDK 5.5.0, you can use this version for now.

**Comment by fahad86** [comment]
Ok 1.7, in the manifest file when I changed the apiversion: from 3 to 2 it all started working!

Did it based on this pull request: https://github.com/morinel/gcmpush/pull/35/files
but not sure why that change would fix it
