### ISSUE TITLE
4.1.0 ?

### ISSUE THREAD

**Issue by DouglasHennrich** [morinel/gcmpush#5]
This module works on `Ti 4.1.0.GA` ?

**Comment by morinel** [comment]
I haven't tested it with this particular version (only 4.0), but I assume it should work without any problems.

**Comment by DouglasHennrich** [comment]
huum
I ask this because I was using GCM module from iamyellow and it stop work on version `4x`.

So your module work fine on `4x` ? Great :D

There's any problem when the user touch the alert and open the app ?

Because I tried to use Parse module and it freeze my app when I touch on an push alert =/

**Comment by morinel** [comment]
> There's any problem when the user touch the alert and open the app ?

Not that I know off, but of course it depends on what you're doing in your app when the notification is opened ;-)

> Because I tried to use Parse module and it freeze my app when I touch on an push alert =/

Try it with simpler logic (without Parse) whether that works, then Parse without push and then with both.

Good luck!

**Comment by DouglasHennrich** [comment]
Thanks for your time @morinel ! I will use your module and test ^^

**Comment by DouglasHennrich** [comment]
It work!!

I love you s2 hahaha
