### ISSUE TITLE
Click listener on notifications in android

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [morinel/gcmpush#62]
Is there any way to add listener when user click on notifications on android ?

**Comment by morinel** [comment]
See https://github.com/morinel/gcmpush/blob/master/example/app.js#L40-57

**Comment by MahmoudElmoghazy** [comment]
@morinel I know the callback but i wont fire function when user click on it like this
`  CloudPush.addEventListener('callback', function (evt) {
        Ti.API.info('Inside CloudPush-Callback.');
    });
    CloudPush.addEventListener('trayClickLaunchedApp', function (evt) {
        Ti.API.info('Inside CloudPush-trayClickLaunchedApp. Payload => ' +  evt.payload);
    });
    // Triggered when the push notifications is in the tray when the app is running
    CloudPush.addEventListener('trayClickFocusedApp', function (evt) {
        Ti.API.info('Inside CloudPush-trayClickFocusedApp. Payload => ' +  evt.payload);
    }); `

**Comment by morinel** [comment]
Right, I'm open for pull requests from any developers implementing this feature.

**Comment by MahmoudElmoghazy** [comment]
@morinel Ok thanks man for help :)

**Comment by mark22** [comment]
Any update to this?  Seems like a critical feature to know if a user actually opened the app by clicking a notification?

**Comment by MahmoudElmoghazy** [comment]
@mark22 You can fix this issue by make local notifications thats fire when notifications revice and put you callback on it

**Comment by mark22** [comment]
@MahmoudElmoghazy Sounds interesting!  Any possibility of posting up some code, I don't exactly follow how to do it.  Thank you!

**Comment by MahmoudElmoghazy** [comment]
yes sure i will make app with local notifications this next saturday and i will upload it to github and i will inform you don't worry

**Comment by mark22** [comment]
Ti.Goosh seems to have solved the issue, maybe the solution for us is something similar?

https://github.com/caffeinalab/ti.goosh/commit/22924ee861ae3e05f6fb2b2710db34521f0a8d4e

**Comment by MahmoudElmoghazy** [comment]
@mark22 Thank u for this module this module is the one 
https://github.com/caffeinalab/ti.goosh
