### ISSUE TITLE
Android "big view" notifications

### ISSUE THREAD

**Issue by lawjeremy** [morinel/gcmpush#9]
Is it possible to use big view notifications on Android so that the message body isn't truncated?

**Comment by morinel** [comment]
No, not yet. Want to provide a patch? ;-)

**Comment by lawjeremy** [comment]
I'll see what I can do when I wrap up my current project.

**Comment by kopiro** [comment]
I think you can just set `priority` to `2`

**Comment by lawjeremy** [comment]
No, setting the priority doesn't achieve what I am looking for. To get expandable notifications in the tray, I needed to add BigTextStyle to the Notification builder. I have this working in my project, and will submit a pull request for review.
